# Generated by Django 5.0.2 on 2024-02-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_table',
            name='inventory',
            field=models.SmallIntegerField(),
        ),
    ]
